### ISSUE TITLE
Policies not found

### ISSUE THREAD

**Issue by fbuinosquy1985** [reposaur/reposaur#5]
Hello i set the following GH action 

`

      - run: |
          set -e
          set -o pipefail
          os="Linux"
          arch="$(uname -m)"
          repo="reposaur/reposaur"
          tag="v0.4.0"
          filename=""
          url="https://github.com/$repo/releases/download/$tag/reposaur_${tag#v}_${os}_${arch}.tar.gz"
          rm -f reposaur.tar.gz
          curl -sL "$url" > reposaur.tar.gz
          tar zxf reposaur.tar.gz
          rm reposaur.tar.gz
          echo "${{ github.action_path }}" >> $GITHUB_PATH
          sudo cp -f reposaur /usr/local/bin
          sudo cp -f reposaur /usr/bin
          curl -fsSL https://cli.github.com/packages/githubcli-archive-keyring.gpg | sudo dd of=/usr/share/keyrings/githubcli-archive-keyring.gpg
          echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" | sudo tee /etc/apt/sources.list.d/github-cli.list > /dev/null
          sudo apt update
          sudo apt install -y gh         
          pwd         
          gh api /orgs/callruby/repos --paginate \
          | reposaur -p $PWD/policy \
          | jq -r '.[] | @base64' \
          | {
            while read r; do
              _r() {
                echo ${r} | base64 -d | jq -r ${1}
              }

              owner=$(_r '.runs[0].properties.owner')
              repo=$(_r '.runs[0].properties.repo')
              branch=$(_r '.runs[0].properties.default_branch')
              commit_sha=$(gh api "/repos/$owner/$repo/branches/$branch" | jq -r '.commit.sha')

              # We've some internal repositories that don't have access to Advanced Security
              # features, since we're on a free plan. Thus the `|| true` in end of the command,
              # to avoid the workflow to exit unsuccessfully in such cases.
              gh api "/repos/$owner/$repo/code-scanning/sarifs" \
                -f sarif="$(_r '.' | gzip | base64)" \
                -f commit_sha="$commit_sha" \
                -f ref="refs/heads/$branch" || true 
            done
          }
`

and when the pipeline is executed it throws 

`
Error: no policies found in [/home/runner/_work/ruby-reposaur/ruby-reposaur/policy]
`

**Of course the policy folder is set on the repository**

Thoughts ?

**Comment by crqra** [comment]
I'm already setting up a self-hosted runner on GCP using the image you provided to test this throughly. I'll update you on my findings as soon as I have something.

**Comment by crqra** [comment]
@fbuinosquy1985 Finally managed to test your use case, with the same image you're using (deployed it to GCP) and it seems to be working fine...

Example run (don't mind the Advanced Security errors as I don't have them enabled on that org):
https://github.com/crqra-demo-org/test-reposaur-self-hosted-runner/runs/6117234821?check_suite_focus=true

The workflow:
https://github.com/crqra-demo-org/test-reposaur-self-hosted-runner/blob/main/.github/workflows/audit.yml

---

Looks like your problem might be related with something else. If you want, we can schedule a 10 minutes call to debug this together. You can also join our Slack ([invitation link](https://join.slack.com/t/reposaur/shared_invite/zt-17g48711z-45nnGyM7zKVAI2Oo319GuQ)).

**Comment by fbuinosquy1985** [comment]
well after the chat we have, the error was a silly one , the policy extension has to be .rego

**Comment by crqra** [comment]
Thank you for the feedback @fbuinosquy1985. We've opened another issue to keep track of improving the error message in this particular case to improve the UX: #8.
