### ISSUE TITLE
Improve the error message when valid policy paths are given but no policies are found

### ISSUE THREAD

**Issue by crqra** [reposaur/reposaur#8]
The current error message when we specify a valid policy paths that doesn't has any policies in inside is:

```
Error: no policies found in [/home/runner/_work/ruby-reposaur/ruby-reposaur/policy]
```

This error can be further improved by providing the user with suggestions such as "make sure your policy files have the the `.rego` extension". Maybe other suggestions would be also good like if we find `.go` files suggesting if it shouldn't be `.rego`.

Looking for feedback on this one.

**Comment by jsmvaldivia** [comment]
I'd suggest creating an error with a specific suggestion list besides the error message. You could even pass the file list to the error so you could properly check and suggest accordingly.

As valid suggestions I pretty much agree with what you propose, I'd say you could build a bigger error message such as the one that follows
```
Error: no policies found in [/home/runner/_work/yadayada/policy]
Possible causes:
- Make sure your policy files have the .rego extension
- The files present have a .go extension
- There is no file present in the given path
```

The only downfall I see is the logs becoming a bit verbose

```go
type PolicyFileError struct {
    Path string
    FoundFiles []string
}

func (e *PolicyFileError) Error() string {
  //actual code to build the error based on the path and the files
}


```

**Comment by crqra** [comment]
Good idea! 💡 

I'd just do some adjustments to the causes copy:

```
- The files present don't have a `.rego` extension
^ - combines the first two sentences into one
- No files found in the given path
^ - just shorter version of the sentence
```

Alternatively we could present the causes conditionally based on the actual files we've found instead of just throwing all possible causes to the user.

I think it's better for the error to be named `PolicyLoaderError` since it is related with the [loading process](https://github.com/reposaur/reposaur/blob/main/internal/policy/engine.go#L179-L185) and not with a particular policy file.

Would you like to pick this one? 💪🏼

**Comment by jsmvaldivia** [comment]
@crqra yes, I'll assign it to myself. Sounds like a good first issue 👍🏼 I agree with the adjustments also
